In [29]:
import pandas

In [30]:
ds=pandas.read_csv('Salary_Data.csv')

In [31]:
ds

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [32]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [33]:
ds.info

<bound method DataFrame.info of     YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872>

In [34]:
x=ds['YearsExperience'].values.reshape(30,1)

In [35]:
y=ds['Salary']

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
model=LinearRegression()

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
#train_test_split()
#shift+tab
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [40]:
X_train.shape

(24, 1)

In [41]:
X_test.shape

(6, 1)

In [42]:
model.fit(X_train,y_train)

LinearRegression()

In [43]:
model.predict(X_test)

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

In [44]:
model.coef_

array([9423.81532303])

In [45]:
model.predict([[2.5]])

array([48881.12131935])

In [46]:
c=model.intercept_

In [47]:
c

25321.583011776813

In [48]:
model

LinearRegression()

In [49]:
import joblib

In [50]:
joblib.dump(model,'darrsheni_salary.pk1')

['darrsheni_salary.pk1']